param(
    [string]$InternalBranch = "main",
    [string]$PublicBranch = "public-main",
    [string]$PublicRemote = "public",
    [string]$WorktreePath = (Join-Path (Split-Path -Parent $PSScriptRoot) "DataBase-public"),
    [string]$SanitizeScript = "",
    [string]$CommitMessage = "",
    [switch]$AllowDirty,
    [switch]$SkipLeakGuard,
    [switch]$Push,
    [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = $PSScriptRoot

function Invoke-Git {
    param(
        [Parameter(Mandatory = $true)][string[]]$Args,
        [string]$WorkingDirectory = $repoRoot,
        [switch]$Mutates
    )

    $display = "git " + ($Args -join " ")
    if ($DryRun -and $Mutates) {
        Write-Host "[dry-run] $display"
        return @()
    }

    Push-Location $WorkingDirectory
    try {
        $output = & git @Args 2>&1
        $exitCode = $LASTEXITCODE
    }
    finally {
        Pop-Location
    }

    if ($exitCode -ne 0) {
        throw "Command failed ($exitCode): $display`n$($output -join [Environment]::NewLine)"
    }

    return $output
}

function Test-Git {
    if (-not (Get-Command git -ErrorAction SilentlyContinue)) {
        throw "git is not available in PATH."
    }

    Push-Location $repoRoot
    try {
        & git rev-parse --is-inside-work-tree *> $null
        if ($LASTEXITCODE -ne 0) {
            throw "Not a git working tree: $repoRoot"
        }
    }
    finally {
        Pop-Location
    }
}

function Resolve-OptionalPath {
    param([string]$PathValue)

    if ([string]::IsNullOrWhiteSpace($PathValue)) {
        return ""
    }

    if ([System.IO.Path]::IsPathRooted($PathValue)) {
        return $PathValue
    }

    return (Join-Path $repoRoot $PathValue)
}

Test-Git

$status = Invoke-Git -Args @("status", "--porcelain")
if ($status.Count -gt 0 -and -not $AllowDirty) {
    throw "Working tree is dirty. Re-run with -AllowDirty if this is intentional."
}

Invoke-Git -Args @("show-ref", "--verify", "--quiet", "refs/heads/$InternalBranch")

if ($Push) {
    Invoke-Git -Args @("remote", "get-url", $PublicRemote)
}

$publicBranchExists = $true
try {
    Invoke-Git -Args @("show-ref", "--verify", "--quiet", "refs/heads/$PublicBranch")
}
catch {
    $publicBranchExists = $false
}

$worktreeGitFile = Join-Path $WorktreePath ".git"
if ((Test-Path $WorktreePath) -and -not (Test-Path $worktreeGitFile)) {
    throw "Worktree path exists but is not a git worktree: $WorktreePath"
}

if (-not (Test-Path $worktreeGitFile)) {
    if ($publicBranchExists) {
        Invoke-Git -Args @("worktree", "add", $WorktreePath, $PublicBranch) -Mutates
    }
    else {
        Invoke-Git -Args @("worktree", "add", "-b", $PublicBranch, $WorktreePath, $InternalBranch) -Mutates
        $publicBranchExists = $true
    }
}

Invoke-Git -Args @("checkout", $PublicBranch) -WorkingDirectory $WorktreePath -Mutates
Invoke-Git -Args @("reset", "--hard", "refs/heads/$InternalBranch") -WorkingDirectory $WorktreePath -Mutates
Invoke-Git -Args @("clean", "-fdx") -WorkingDirectory $WorktreePath -Mutates

if ($DryRun) {
    $sanitizeScriptPath = Resolve-OptionalPath -PathValue $SanitizeScript
    if (-not [string]::IsNullOrWhiteSpace($sanitizeScriptPath)) {
        Write-Host "[dry-run] powershell -NoProfile -ExecutionPolicy Bypass -File `"$sanitizeScriptPath`" -RepoRoot `"$WorktreePath`""
    }
    if (-not $SkipLeakGuard) {
        Write-Host "[dry-run] run leak guard checks"
    }
    Write-Host "[dry-run] git add -A"
    Write-Host "[dry-run] git commit -m <auto-generated-or-custom-message>"
    if ($Push) {
        Write-Host "[dry-run] git push $PublicRemote ${PublicBranch}:${PublicBranch}"
    }
    Write-Host "Dry-run completed. No changes were made."
    return
}

$sanitizeScriptPath = Resolve-OptionalPath -PathValue $SanitizeScript
if (-not [string]::IsNullOrWhiteSpace($sanitizeScriptPath)) {
    if (-not (Test-Path $sanitizeScriptPath)) {
        throw "Sanitize script not found: $sanitizeScriptPath"
    }

    $command = "powershell -NoProfile -ExecutionPolicy Bypass -File `"$sanitizeScriptPath`" -RepoRoot `"$WorktreePath`""
    if ($DryRun) {
        Write-Host "[dry-run] $command"
    }
    else {
        Push-Location $WorktreePath
        try {
            & powershell -NoProfile -ExecutionPolicy Bypass -File $sanitizeScriptPath -RepoRoot $WorktreePath
            if ($LASTEXITCODE -ne 0) {
                throw "Sanitize script failed with exit code $LASTEXITCODE"
            }
        }
        finally {
            Pop-Location
        }
    }
}

if (-not $SkipLeakGuard) {
    Write-Host "Leak guard checks are currently disabled for unified-only sync workflow."
}

Invoke-Git -Args @("add", "-A") -WorkingDirectory $WorktreePath -Mutates

$hasStagedChanges = $true
try {
    Invoke-Git -Args @("diff", "--cached", "--quiet") -WorkingDirectory $WorktreePath
    $hasStagedChanges = $false
}
catch {
    $hasStagedChanges = $true
}

if ($hasStagedChanges) {
    if ([string]::IsNullOrWhiteSpace($CommitMessage)) {
        $sourceCommit = (Invoke-Git -Args @("rev-parse", "--short", "refs/heads/$InternalBranch"))[0]
        $CommitMessage = "Sync public branch from $InternalBranch @$sourceCommit"
    }
    Invoke-Git -Args @("commit", "-m", $CommitMessage) -WorkingDirectory $WorktreePath -Mutates
}
else {
    Write-Host "No public-branch changes to commit."
}

if ($Push) {
    Invoke-Git -Args @("push", $PublicRemote, "${PublicBranch}:${PublicBranch}") -WorkingDirectory $WorktreePath -Mutates
}

Write-Host "Public sync flow completed."
Write-Host "Worktree: $WorktreePath"
Write-Host "Public branch: $PublicBranch"
if ($Push) {
    Write-Host "Push: completed to remote '$PublicRemote'."
}
else {
    Write-Host "Push: skipped (use -Push to publish)."
}

